/**
 * trace-skyline.js
 * Converts a black-on-white silhouette PNG into a ready-to-paste SVG OUTLINE_D string.
 *
 * Usage:
 *   node scripts/trace-skyline.js [input.png] [options]
 *
 * Options (edit the CONFIG block below):
 *   STEP       — sample every N columns (default 2 → 720 pts for a 1440px image)
 *   WIN        — sliding-window min radius in columns; bridges sky gaps (default 10)
 *   SVG_TOP    — y coord for the tallest spire tip in the 1440×560 viewBox (default 60)
 *   SVG_GROUND — y coord for the ground line (default 455)
 *
 * Output:
 *   Prints a JS const string you can paste directly into CityHero.tsx as OUTLINE_D.
 *   Also prints the start-y and the tallest-y / x position.
 *
 * Requirements:
 *   sharp (already in devDependencies)
 *   Run from the project root: node scripts/trace-skyline.js
 */

const sharp = require("sharp");
const path = require("path");

// ── CONFIG ────────────────────────────────────────────────────────────────────
const INPUT = path.resolve("public/nyc.png"); // ← swap to nyc.png / tokyo.jpg
const TARGET_W = 1440; // resize image to this width before tracing
const STEP = 2; // sample every N columns (lower = more points, smoother)
const WIN = 10; // sliding-window min radius (higher = bridges wider gaps)
const SVG_TOP = 60; // tallest-spire y in SVG viewBox
const SVG_GROUND = 455; // ground-line y in SVG viewBox
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  const { data, info } = await sharp(INPUT)
    .resize(TARGET_W, null, { fit: "inside" })
    .greyscale()
    .threshold(128)
    .raw()
    .toBuffer({ resolveWithObject: true });

  const { width, height } = info;
  console.error(`Image: ${width}×${height}`);

  // 1. Find topmost black pixel per column
  const raw = [];
  for (let x = 0; x < width; x += STEP) {
    let topY = null;
    for (let y = 0; y < height; y++) {
      if (data[y * width + x] < 128) {
        topY = y;
        break;
      }
    }
    if (topY !== null) raw.push({ x, y: topY });
  }

  // 2. Sliding-window minimum — bridges narrow sky gaps between buildings
  const smoothed = raw.map((pt, i) => {
    let minY = pt.y;
    for (
      let j = Math.max(0, i - WIN);
      j <= Math.min(raw.length - 1, i + WIN);
      j++
    ) {
      if (raw[j].y < minY) minY = raw[j].y;
    }
    return { x: pt.x, y: minY };
  });

  // 3. Scale into SVG viewBox 0 0 1440 560
  const imgMinY = Math.min(...smoothed.map((p) => p.y));
  const imgMaxY = Math.max(...smoothed.map((p) => p.y));

  const pts = smoothed.map((p) => ({
    x: p.x,
    y: Math.round(
      SVG_TOP +
        ((p.y - imgMinY) / (imgMaxY - imgMinY)) * (SVG_GROUND - SVG_TOP),
    ),
  }));

  // 4. Build path string
  let d = `M ${pts[0].x} ${pts[0].y}`;
  for (let i = 1; i < pts.length; i++) d += ` L ${pts[i].x} ${pts[i].y}`;
  d += ` L 1440 ${SVG_GROUND}`;

  const tallest = pts.reduce((a, b) => (b.y < a.y ? b : a));

  console.log(
    `// Auto-generated by scripts/trace-skyline.js from ${path.basename(INPUT)}`,
  );
  console.log(
    `// STEP=${STEP}  WIN=${WIN}  SVG_TOP=${SVG_TOP}  SVG_GROUND=${SVG_GROUND}`,
  );
  console.log(
    `// Tallest: y=${tallest.y} at x=${tallest.x}  |  Start y=${pts[0].y}`,
  );
  console.log(`const OUTLINE_D = "${d}";`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
